# Generated by Django 4.2.2 on 2024-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Required. Inform a valid country.', max_length=35, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Required. Inform a valid phone number.', max_length=35, null=True, verbose_name='Phone Number'),
        ),
    ]
