# Generated by Django 5.0.3 on 2024-04-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogrecord',
            options={'ordering': ['published_at'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
