# Generated by Django 5.0.3 on 2024-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecord',
            name='published_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата публикации'),
        ),
    ]
