# Generated by Django 5.0.3 on 2024-04-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogrecord_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecord',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации'),
        ),
    ]
