# Generated by Django 4.2.2 on 2024-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошел модерацию'),
        ),
    ]
